on:
  push:
    branches:
      - master
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan migrate:fresh --seed
    - name: Generate keygegwew
      run: npm install
    - name: Generate keywegwg
      run: npm run prod
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: asrafporag.me
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /home/asraf/rappi-farma-admin.asrafporag.me/rappi
