on:
  push:
    branches:
      - master
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.3'
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer update
    - name: Seeding database
      run: php artisan migrate:fresh --seed
    - name: install npm
      run: npm install
    - name: Run production
      run: npm run prod
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: asrafporag.me
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /home/asraf/rappi-farma-admin.asrafporag.me/rappi
